version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mx70_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mx70_network

  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/mx70_db
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - mx70_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mx70_network
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:

networks:
  mx70_network:
    driver: bridge 